### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by mayeaux** [olieidel/tinder-api-super#1]
```
TinderApi.prototype.sendLike = function(likedUserId, callback) {
  var self = this;
  self.checkAuth();

  if (!likedUserId || typeof likedUserId !== 'string') {
    throw new self.ApiException('Missing likedUserId or not String');
  }

  request.get(
    self.constructReqOpts(TINDER_HOST + '/like/' + likedUserId),
    self.RequestCallback(callback, 'like')
  );
};

TinderApi.prototype.sendSuperLike = function(likedUserId, callback) {
  var self = this;
  self.checkAuth();

  if (!likedUserId || typeof likedUserId !== 'string')
    throw new self.ApiException('Missing likedUserId or not String');

  request.post(
    self.constructReqOpts(TINDER_HOST + '/like/' + likedUserId + '/super'),
    self.RequestCallback(callback, 'superLike')
  );
};
```

Is it actually a get request for one and a post request for the other?

**Comment by olieidel** [comment]
thanks for your question!
yes it is. at least at the time when I recorded the requests (11/2015). super weird and not intuitive (get for like and post for super-like?!). the whole api seems ill-designed.

**Comment by mayeaux** [comment]
where'd you find those other endpoints? I'm probably going to sniff out a bunch of the endpoints this weekend

**Comment by olieidel** [comment]
I sniffed them myself with Charles (SSL Proxy / Sniffer). Good luck!

**Comment by mayeaux** [comment]
Oh very cool! Yeah I just bought Charles last weekend and will sniff them this weekend. Thanks! I think it will be pretty straightforward but maybe I'll ping you if I run into an issue ;D

**Comment by olieidel** [comment]
sure! :)

**Comment by mayeaux** [comment]
You should check something out with me, which is the image upload API.

I've sniffed out a couple more endpoints which I'm going to report in the TInder API gist. However, image upload looks a little funkier. It hits imageupload.gotinder.com , and sends a 'pendingImage.jpg', which is a photo that is edited to be square, and then it passes a userID as well. The funny thing is, I don't think it passes a token! I swear it's totally unauthenticated and you could upload a photo to anyone's profile! You should check it out and see if I'm crazy or not haha!

**Comment by olieidel** [comment]
Interesting stuff!
You may be right, the Tinder API seems bad enough that something like this may be plausible. Regarding the image upload, have you checked the Request Headers (Charles: Select GET/POST item -> Request -> Headers) for an X-Auth-Token? At first I also thought that all Tinder API calls would not be authorized, however I discovered that token later on. If it indeed is missing, you could have found something ;)

Keep me updated!

**Comment by mayeaux** [comment]
Yup, I know about the X-Auth-Token workflow, I'm maintaining the other Tinder JS Api ( http://www.github.com/tinderjs/tinderjs ) , and I could see every called passed that header except this call to imageupload.gotinder.com which like I said only seems to pass a userId and image as far as I can tell.

**Comment by mayeaux** [comment]
I've got a pretty demanding M-F day job so idk how much time I will have to look at it again until the weekend but if it's not too much of a pain you should check out that image upload endpoint call and tell me if we actually found an unauthenticated endpoint. 😀😛

**Comment by olieidel** [comment]
Okay cool, I'll test it at the weekend at the latest. If you are right, it might be quite a "fun" endpoint. :)

**Comment by mayeaux** [comment]
Lmao I swear ;) I want to find if Tinder has a vulnerability reporting you can do for $$$, would be a nice pickup haha ;)

**Comment by olieidel** [comment]
Probably not, guessing by how disorganized their api and how crappy their android app has been in the past.. but we might find out soon!
